# This is a basic workflow to help you get started with Actions

name: CI

on:
  repository_dispatch:
    types: [ new ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: ls -l

      - name: Run a one-line script
        run: sleep 30
